# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FCELd7wRZWPYThGc_1wmch0Trk-OMlIr
"""

def spiral(n):
  mat = [[0]*n for _ in range(n)]
  top = 0
  left = 0
  bottom = n-1
  right = n-1

  current_value = 1

  while top<=bottom and left<=right:
    for col in range(left, right+1):
      mat[top][col]=current_value
      current_value+=1

    top+=1

    for row in range(top, bottom+1):
      mat[row][right] = current_value
      current_value+=1

    right-=1

    if top<=bottom:
      for col in range(right, left-1, -1):
        mat[bottom][col]=current_value
        current_value+=1

      bottom-=1

    if left<=right:
      for row in range(bottom, top-1, -1):
        mat[row][left]=current_value
        current_value+=1

      left+=1

  return mat


n = int(input("Enter the number"))
res = spiral(n)

for row in res:
  print(row)

